version: "3.7"

services:
  db:
    container_name: sirka-be__postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    # volumes:
    #   - ./scripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  server:
    container_name: sirka-be__server
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DOCKER_PORT=:8080
      - DOCKER_DATABASE_URL=postgres://postgres:postgres@db:5432/database

volumes:
  postgres_vol:
